export const ACTORS = [
  { id: 'person',  nom: 'The person',     sub: 'Decides' },
  { id: 'agent',   nom: 'The agent',      sub: 'Runs the five steps' },
  { id: 'gates',   nom: 'The gates',      sub: 'Inherit the premise' },
  { id: 'replica', nom: 'Blind replica',  sub: 'Never sees the reasoning' },
]

export const COLUMNS = [
  { id: 'c1', nom: '1 · Plan' },
  { id: 'c2', nom: '2 · Build' },
  { id: 'c3', nom: '3 · End to end' },
  { id: 'c4', nom: '4 · QA of the QA' },
  { id: 'c5', nom: '5 · Verify' },
]

export const NODES = [
  { id: 'ok',  actor: 'person', col: 'c1', titulo: 'Plan approved', clave: 'shared understanding',
    sub: 'Nothing is written before this' },
  { id: 'pv',  actor: 'person', col: 'c5', titulo: 'The question before', clave: 'before saying something outward',
    sub: 'Does it need saying, or do it and explain?' },
  { id: 'mrg', actor: 'person', col: 'c5', titulo: 'Whoever merges decides', clave: 'whether the PR can merge',
    sub: 'With the verdict in hand' },

  { id: 'p1',  num: '1',  actor: 'agent', col: 'c1', titulo: 'Plan', fuerte: true,
    sub: 'Interview to shared understanding' },
  { id: 'p1b', num: '1b', actor: 'agent', col: 'c1', titulo: 'The fork', desvio: true,
    sub: 'Fits in ONE session? ~140k useful' },
  { id: 'p1c', num: '1c', actor: 'agent', col: 'c1', titulo: 'Spec and tickets', desvio: true,
    sub: 'If it does not fit · session-sized' },
  { id: 'p2',  num: '2',  actor: 'agent', col: 'c2', titulo: 'Build', fuerte: true,
    sub: 'Build → tests first → review → commit' },
  { id: 'p2b', num: '2b', actor: 'agent', col: 'c2', titulo: 'Diagnose', desvio: true,
    sub: 'Only if broken · before patching' },
  { id: 'p3',  num: '3',  actor: 'agent', col: 'c3', titulo: 'End to end', fuerte: true,
    sub: 'Run on real data and LOOK' },
  { id: 'p4',  num: '4',  actor: 'agent', col: 'c4', titulo: 'QA of the QA', fuerte: true,
    sub: 'Falsify the oracle, no easy mutation' },
  { id: 'p5',  num: '5',  actor: 'agent', col: 'c5', titulo: 'Verify', fuerte: true,
    sub: 'Measure again at the real source' },

  { id: 'g1', actor: 'gates', col: 'c2', titulo: 'Fidelity reviewer',
    sub: 'Did you build what was agreed?' },
  { id: 'g2', actor: 'gates', col: 'c4', titulo: 'Format gate',
    sub: 'How it is written. Reads no code' },
  { id: 'g3', actor: 'gates', col: 'c5', titulo: 'Refuter',
    sub: 'Tries to knock it down with code and data' },
  { id: 'g4', actor: 'gates', col: 'c5', titulo: 'Merge gate',
    sub: 'Says mergeable, never decides' },

  { id: 'frz', actor: 'replica', col: 'c1', titulo: 'Freeze', desvio: true, clave: 'the claim and the sources are frozen',
    sub: 'The claim and the sources' },
  { id: 'g5', actor: 'replica', col: 'c5', titulo: 'Blind replica',
    sub: 'Delivers sealed BEFORE seeing yours' },
]

export const EDGES = [
  { de: 'p1',   a: 'ok',   tipo: 'flujo' },
  { de: 'p1',   a: 'p1b',  tipo: 'flujo' },
  { de: 'p1b',  a: 'p1c',  tipo: 'desvio', etiqueta: 'Does not fit' },
  { de: 'p1c',  a: 'p2',   tipo: 'desvio' },
  { de: 'ok',   a: 'p2',   tipo: 'flujo',  etiqueta: 'Only now is anything written' },
  { de: 'p2',   a: 'g1',   tipo: 'puerta' },
  { de: 'g1',   a: 'p2',   tipo: 'retorno', etiqueta: 'If a gate fails, fix the TEST before the code' },
  { de: 'p2',   a: 'p2b',  tipo: 'desvio', etiqueta: 'Broken' },
  { de: 'p2b',  a: 'p2',   tipo: 'retorno' },
  { de: 'p2',   a: 'p3',   tipo: 'flujo' },
  { de: 'p3',   a: 'p4',   tipo: 'flujo' },
  { de: 'p4',   a: 'g2',   tipo: 'puerta' },
  { de: 'p4',   a: 'p5',   tipo: 'flujo' },
  { de: 'p5',   a: 'g3',   tipo: 'puerta' },
  { de: 'g3',   a: 'g4',   tipo: 'puerta' },
  { de: 'g4',   a: 'mrg',  tipo: 'puerta' },
  { de: 'pv',   a: 'mrg',  tipo: 'flujo',   etiqueta: 'Before escalating it as a decision' },
  { de: 'p3',   a: 'p1',   tipo: 'retorno', etiqueta: 'Two failures of the same hypothesis' },
  { de: 'p1',   a: 'frz',  tipo: 'paralelo' },
  { de: 'frz',  a: 'g5',   tipo: 'paralelo', etiqueta: 'Runs in parallel, without seeing the calculation' },
  { de: 'g5',   a: 'p5',   tipo: 'puerta',   etiqueta: 'Only now are the two compared' },
]

export const GATES = [
  { id: 'g1', en: 'p2', nombre: 'Fidelity reviewer' },
  { id: 'g2', en: 'p4', nombre: 'Format gate' },
  { id: 'g3', en: 'p5', nombre: 'Refuter' },
  { id: 'g4', en: 'p5', nombre: 'Merge gate' },
  { id: 'g5', en: 'p5', nombre: 'Blind replica' },
]

export const LANES = [
  { id: 'l-query',      nom: 'Query',                  que: 'Measure and answer',             pasos: false },
  { id: 'l-mechanical', nom: 'Mechanical change',      que: 'Only if proven. Step 3',         pasos: false },
  { id: 'l-code',       nom: 'Code with logic',        que: 'The five steps',                 pasos: true  },
  { id: 'l-data',       nom: 'Data to a third party',  que: 'Step 3 plus protocol',           pasos: false },
  { id: 'l-text',       nom: 'Text',                   que: 'Format gate plus refuter',       pasos: false },
]

export const ROUTING_QUESTION = 'Can you PROVE it changes no executable behavior, stored data, permissions, integration or deployment?'
export const ROUTING_SUB = 'If you cannot prove it, it is code. The burden of proof is on the cheap lane, not the expensive one.'

export const TRANSVERSAL = [
  'Every claim is a hypothesis until measured by an independent route',
  'The instrument is calibrated on the real corpus, and whoever calibrates says what was NOT tested',
  'A line enters the method only if it turns red on its historical case',
]

export const CARDS = {
  pv: { t: 'The question before',
    c: ['Does it need saying, or can it be done and explained afterwards? Does it really move something outside, or is it being treated as risky without checking?',
        'It sits HERE and not at the start. The method titles it "before saying something outward", before communicating a decision, not before building.'],
    skill: 'No command, two questions' },
  ok: { t: 'The plan approved',
    c: ['The interview runs inside plan mode. What step 1 writes, context, decisions, spec, is written AFTER the approval, never before.'],
    skill: 'Plan mode of the terminal' },
  mrg: { t: 'Whoever merges decides',
    c: ['The merge gate says whether the PR is mergeable. It does not decide whether it gets merged.',
        'Its findings are reproduced with your own test before being repeated as facts. Only what it marks as mandatory forces a fix.'],
    skill: 'None, it is a decision' },
  p1: { t: 'Step 1, Plan',
    c: ['The interview that sharpens the idea into shared understanding, and leaves a record.',
        'The agent starts it on its own. The person answers decisions, not the method.'],
    skill: 'mattpocock-skills:grilling · or /grill-with-docs by hand' },
  p1b: { t: '1b, the fork',
    c: ['Decide whether the work fits in ONE session, about 140k tokens of useful context.',
        'No command, it is judgment. The agent estimates it when closing the interview and SAYS SO.'],
    skill: 'No command, it is judgment' },
  p1c: { t: '1c, spec and tickets',
    c: ['Only if it does NOT fit. The destination and the path are written as session-sized tickets.',
        'One ticket, one session.'],
    skill: '/to-spec then /to-tickets by hand' },
  p2: { t: 'Step 2, Build',
    c: ['The orchestrator chain, with the fidelity reviewer as its close.',
        'Tests first for every piece of logic that can break. The seams were agreed in step 1, not here.'],
    skill: 'Build → tdd → code-review in clean subagents → commit' },
  p2b: { t: '2b, diagnose',
    c: ['Only if it is broken. Diagnose BEFORE patching.',
        'Patching without diagnosing moves the bug instead of removing it.'],
    skill: 'mattpocock-skills:diagnosing-bugs' },
  p3: { t: 'Step 3, End to end',
    c: ['Run on real data and LOOK at the result. With your eyes.',
        'Name the surface where a person will see it BEFORE looking, then look at THAT surface.',
        'Two failures of the same functional hypothesis send you back to step 1. An environmental failure is diagnosed and does not count.',
        'Looking is not a more expensive test. It is the only act that brings in information from outside the model.'],
    skill: 'No skill, run the real thing' },
  p4: { t: 'Step 4, QA of the QA',
    c: ['Falsify the oracle, do not pick a convenient mutation. Three requirements.',
        'Reintroduce the EXACT defect, add a semantic counterexample chosen separately, and confirm the test fails FOR THE EXPECTED REASON and not just that something turns red.'],
    skill: 'Controlled injection + hooks/format-gate.sh --strict' },
  p5: { t: 'Step 5, Verify',
    c: ['Check the exit condition on the real source or surface.',
        'A figure gets measured again by another route, in the normal state and in the edge state. A behavior change gets observed at the destination.',
        'Neither an earlier run nor a document is cited as a substitute for reality.'],
    skill: 'Measure again against the source' },
  g1: { t: 'Gate, fidelity reviewer',
    c: ['Decides whether what was AGREED got built. Runs on two blind axes, standards and spec, in clean subagents.',
        'Not whether it is well built in the abstract, but whether it is what step 1 agreed.'],
    skill: 'mattpocock-skills:code-review' },
  g2: { t: 'Gate, format gate',
    c: ['Reviews how the deliverable is WRITTEN. Em-dashes, colons in prose, counts a diff can disprove.',
        'Reads no code and finds no bugs. It is one half of step 4, not the working model.'],
    skill: 'hooks/format-gate.sh --strict' },
  g3: { t: 'Gate, refuter',
    c: ['An agent whose job is to KNOCK DOWN the finding, not confirm it. Against code and data.',
        'A finding from an agent is NOT a fact. If it dies, why it died gets recorded.'],
    skill: 'Adversarial agent in a clean subagent' },
  g4: { t: 'Gate, merge gate',
    c: ['Decides whether the PR is mergeable, and nothing else. NOT a reviewer with superior judgment.',
        'Its findings are reproduced with your own test before being repeated as facts.'],
    skill: 'The CI or bot check on the PR' },
  frz: { t: 'Freeze the claim',
    c: ['The replica lane starts here. The claim and the sources are frozen.',
        'From this point the replica works in parallel, without seeing the calculation or the reasoning.'],
    skill: 'hooks/blind-replica.sh <brief>' },
  g5: { t: 'Gate, blind replica',
    c: ['The only gate that can break a shared premise, because the other four inherit it.',
        'It receives the claim and the sources, NEVER the calculation. It returns its figure, its method and its premises, and only then are the two compared.',
        'Mandatory with derived figures, platform semantics, ambiguous sources, data to third parties and hard-to-revert consequences.',
        'Single-model mode: a fresh-context subagent. Independence of derivation, not of engine, and the method says so. PRISMA_AUDITOR_CMD plugs in a second engine.'],
    skill: 'hooks/blind-replica.sh' },
}
